### ISSUE TITLE
Modding tutorial

### ISSUE THREAD

**Issue by ghost** [Desno365/Pi-Mod-for-Minecraft-PE#1]
Hi @Desno365!

First things first: I absolutely love your mods and I am overjoyed that they work woth every version of MCPE until now. However, I am a developer who is fluent in quite a few languages and I wanted to try my hand at modding, I tried reading the source code of some of your mods but to no avail. What I would like to do: Bring a custom item into the game which has a texture created by me and shoots out flames which kill instantly. This is just an idea but I have no idea how to add items to the game, set their texture, crafting recipe and behaviour. If you could maybe write a tutorial on this on your excellent site or just message me and maybe guide me through the process of implementing afore-mentioned item into the game as a mod, I would be much obliged to you!

**Comment by Desno365** [comment]
Hi!
Unfortunately I don't have the time to guide you step by step but I can show some of the best way to gain knowledge. 
First you can start reading some of the already existing modding guides, like this one https://github.com/Connor4898/ModPE-Scripts/wiki/ModPE-Scripts-Functions-List
Unfortunately, for what I know, there isn't any up to date guide, but at least you gain some knowledge. 
In these guides you will find hooks (that are things that the game calls and then you can process) and methods (that are things that your code can call to make the game do whatever you want).
Then you need to know a bit of Javascript.

If you want to use also Buttons and UIs you will also need to know a bit of Android developing. You can search the Android reference and the web for more specific things.

And finally you can read other people's code. I learned in that way! But my mods are already complex, so I would suggest to read some other simpler js mods and make small modifications.

P.S.: .modpkg files are just .zip files renamed

**Comment by Desno365** [comment]
I also made many years ago a little tutorial on how to make android UIs: https://www.minecraftforum.net/forums/minecraft-pocket-edition/mcpe-mods-tools/mcpe-mod-tool-discussion/2097308-tutorial-how-to-add-an-android-gui-in-your-mod-by
It's not that good, but you may find it useful to start.
